// <auto-generated />
using System;
using BackendProject.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendProject.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendProject.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Backend Developing department",
                            IsDeleted = false,
                            Name = "Backend Developing"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Core engineering and infrastructure team",
                            IsDeleted = false,
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Sales and customer relations department",
                            IsDeleted = false,
                            Name = "Sales"
                        });
                });

            modelBuilder.Entity("BackendProject.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            DepartmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "panagiotis.stavrakellis@company.com",
                            FirstName = "Panagiotis",
                            HireDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LastName = "Stavrakellis",
                            Notes = "Backend Developer",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            DepartmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "nikolaos.papadopoulos@company.com",
                            FirstName = "Nikolaos",
                            HireDate = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LastName = "Papadopoulos",
                            Notes = "Frontend Developer",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Email = "georgios.konstantinidis@company.com",
                            FirstName = "Georgios",
                            HireDate = new DateTime(2019, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LastName = "Konstantinidis",
                            Notes = "DevOps Engineer",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Email = "maria.georgiou@company.com",
                            FirstName = "Maria",
                            HireDate = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LastName = "Georgiou",
                            Notes = "QA Engineer",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            DepartmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "eleni.dimitriou@company.com",
                            FirstName = "Eleni",
                            HireDate = new DateTime(2020, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LastName = "Dimitriou",
                            Notes = "Frontend Developer",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000003"),
                            DepartmentId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Email = "dimitrios.antonopoulos@company.com",
                            FirstName = "Dimitrios",
                            HireDate = new DateTime(2018, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LastName = "Antonopoulos",
                            Notes = "Former Project Manager",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000004"),
                            DepartmentId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Email = "konstantina.vasileiou@company.com",
                            FirstName = "Konstantina",
                            HireDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LastName = "Vasileiou",
                            Notes = "Sales Representative",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000005"),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Email = "athanasios.nikolaidis@company.com",
                            FirstName = "Athanasios",
                            HireDate = new DateTime(2021, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LastName = "Nikolaidis",
                            Notes = "Database Administrator",
                            Status = 0
                        });
                });

            modelBuilder.Entity("BackendProject.Domain.Entities.EmployeeProject", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmployeeId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("EmployeeProjects", (string)null);

                    b.HasData(
                        new
                        {
                            EmployeeId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            ProjectId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            EmployeeId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            ProjectId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            EmployeeId = new Guid("00000000-0000-0000-0001-000000000001"),
                            ProjectId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            EmployeeId = new Guid("00000000-0000-0000-0002-000000000002"),
                            ProjectId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            EmployeeId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            ProjectId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            EmployeeId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            ProjectId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            EmployeeId = new Guid("00000000-0000-0000-0005-000000000005"),
                            ProjectId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            EmployeeId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            ProjectId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            EmployeeId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            ProjectId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        });
                });

            modelBuilder.Entity("BackendProject.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Projects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "Technical assessment project for evaluating backend development skills",
                            EndDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Backend Developer Technical Assessment",
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Description = "Cross-platform mobile application development project",
                            IsDeleted = false,
                            Name = "Mobile Application Platform",
                            StartDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Description = "Legacy system data migration to new cloud infrastructure",
                            EndDate = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Data Migration Initiative",
                            StartDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BackendProject.Domain.Entities.Employee", b =>
                {
                    b.HasOne("BackendProject.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("BackendProject.Domain.Entities.EmployeeProject", b =>
                {
                    b.HasOne("BackendProject.Domain.Entities.Employee", "Employee")
                        .WithMany("EmployeeProjects")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendProject.Domain.Entities.Project", "Project")
                        .WithMany("EmployeeProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BackendProject.Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("BackendProject.Domain.Entities.Employee", b =>
                {
                    b.Navigation("EmployeeProjects");
                });

            modelBuilder.Entity("BackendProject.Domain.Entities.Project", b =>
                {
                    b.Navigation("EmployeeProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
